import { atDallas, nextWeekday } from "./time";
import type {
  Booking,
  ChatMessage,
  HealthSnapshot,
  Person,
  Session,
  Venue,
} from "./types";
import { ME_ID } from "./types";

export const people: Person[] = [
  {
    id: ME_ID,
    name: "Eswara",
    handle: "eswara",
    initials: "EN",
    neighborhood: "Oak Lawn",
    memberSince: "Mar 2026",
    isLead: false,
    bio: "Easy miles before work. Not a trainer.",
    accent: "stand",
    identityVerified: true,
    completedCount: 6,
    onTimePct: 100,
    wouldJoinPct: 100,
  },
  {
    id: "maya",
    name: "Maya Chen",
    handle: "maya",
    initials: "MC",
    neighborhood: "Uptown",
    memberSince: "Jan 2026",
    isLead: true,
    bio: "Katy Trail before standup. Conversation optional.",
    accent: "exercise",
    identityVerified: true,
    completedCount: 41,
    onTimePct: 98,
    wouldJoinPct: 97,
  },
  {
    id: "priya",
    name: "Priya Shah",
    handle: "priya",
    initials: "PS",
    neighborhood: "Lakewood",
    memberSince: "Feb 2026",
    isLead: true,
    bio: "Women-only easy runs. Parks and trails only.",
    accent: "move",
    identityVerified: true,
    completedCount: 28,
    onTimePct: 96,
    wouldJoinPct: 99,
  },
  {
    id: "jordan",
    name: "Jordan Hale",
    handle: "jordan",
    initials: "JH",
    neighborhood: "East Dallas",
    memberSince: "Nov 2025",
    isLead: false,
    bio: "Saturday loops around the lake. Bring water.",
    accent: "stand",
    identityVerified: true,
    completedCount: 19,
    onTimePct: 94,
    wouldJoinPct: 95,
  },
  {
    id: "alex",
    name: "Alex Rivera",
    handle: "alex",
    initials: "AR",
    neighborhood: "Oak Cliff",
    memberSince: "Apr 2026",
    isLead: false,
    bio: "Free park miles. Show up.",
    accent: "fg",
    identityVerified: false,
    completedCount: 11,
    onTimePct: 91,
    wouldJoinPct: 93,
  },
  {
    id: "sam",
    name: "Sam Okonkwo",
    handle: "sam",
    initials: "SO",
    neighborhood: "Uptown",
    memberSince: "Dec 2025",
    isLead: true,
    bio: "Tempo when the weather holds. Not coaching.",
    accent: "exercise",
    identityVerified: true,
    completedCount: 33,
    onTimePct: 97,
    wouldJoinPct: 94,
  },
  {
    id: "dev",
    name: "Dev Patel",
    handle: "dev",
    initials: "DP",
    neighborhood: "Design District",
    memberSince: "Sep 2026",
    isLead: false,
    bio: "Invited from Messages. First in-person seat.",
    accent: "stand",
    identityVerified: false,
    completedCount: 1,
    onTimePct: 100,
    wouldJoinPct: 100,
  },
];

export const venues: Venue[] = [
  {
    id: "katy",
    name: "Katy Trail — Reverchon",
    type: "trail",
    neighborhood: "Uptown",
    lat: 32.8019,
    lng: -96.8074,
    image: "/venues/katy-trail.jpg",
    hint: "East-side pin at the stone trailhead. Parking fills after 6:10.",
  },
  {
    id: "whiterock",
    name: "White Rock Lake — Sunset Bay",
    type: "park",
    neighborhood: "East Dallas",
    lat: 32.8332,
    lng: -96.7281,
    image: "/venues/white-rock.jpg",
    hint: "Loop starts at the bay overlook. Watch the geese on the path.",
  },
  {
    id: "trinity",
    name: "Trinity Forest Trail",
    type: "trail",
    neighborhood: "South Dallas",
    lat: 32.7124,
    lng: -96.7558,
    image: "/venues/trinity-trail.jpg",
    hint: "Trailhead lot off Great Trinity Forest Way. GPS drops under canopy.",
  },
  {
    id: "turtle",
    name: "Turtle Creek Greenbelt",
    type: "park",
    neighborhood: "Oak Lawn",
    lat: 32.8041,
    lng: -96.8079,
    image: "/venues/turtle-creek.jpg",
    hint: "Meet at the limestone bend, not the gym lot.",
  },
];

export function buildHealth(now: Date): HealthSnapshot {
  const yesterday = new Date(now.getTime() - 26 * 60 * 60 * 1000);
  const twoDays = new Date(now.getTime() - 50 * 60 * 60 * 1000);
  return {
    connected: true,
    moveKcal: 420,
    moveGoal: 500,
    exerciseMin: 28,
    exerciseGoal: 30,
    standHours: 8,
    standGoal: 12,
    sleepMin: 7 * 60 + 12,
    hrvMs: 62,
    rhr: 54,
    vo2: 48,
    recoveryPct: 78,
    moveWeek: [510, 640, 380, 720, 455, 590, 420],
    workouts: [
      {
        id: "hw1",
        source: "fitness",
        activity: "run",
        title: "Outdoor Run",
        at: yesterday.toISOString(),
        minutes: 42,
        kcal: 410,
        avgHr: 148,
        distanceKm: 7.8,
      },
      {
        id: "hw2",
        source: "pace",
        activity: "run",
        title: "Katy Trail with Maya",
        at: twoDays.toISOString(),
        minutes: 38,
        kcal: 355,
        avgHr: 141,
        distanceKm: 6.4,
      },
      {
        id: "hw3",
        source: "fitness",
        activity: "strength",
        title: "Functional Strength",
        at: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        minutes: 48,
        kcal: 290,
        avgHr: 122,
      },
    ],
  };
}

export function buildSeedSessions(now: Date): Session[] {
  const liveStart = new Date(now.getTime() - 7 * 60 * 1000);
  const todayPm = nextLocalEvening(now, 18, 0);
  return [
    {
      id: "seed-live",
      seedSlot: "live",
      hostId: "maya",
      venueId: "katy",
      activity: "run",
      title: "Easy 5k I’m doing anyway",
      detail:
        "Conversational pace. If you need a workout plan, this isn’t it — I’m going either way.",
      startAt: liveStart.toISOString(),
      durationMin: 40,
      capacity: 2,
      priceCents: 1500,
      visibility: "public",
      joinMode: "approve",
      womenOnly: false,
      hostAttestsPaidOk: true,
      status: "live",
      code: "4821",
      codeRevealedAt: null,
    },
    {
      id: "seed-today-pm",
      seedSlot: "today-pm",
      hostId: "alex",
      venueId: "turtle",
      activity: "run",
      title: "Shakeout around the creek",
      detail: "Free seat. Public path. Two spots.",
      startAt: todayPm.toISOString(),
      durationMin: 35,
      capacity: 3,
      priceCents: 0,
      visibility: "public",
      joinMode: "instant",
      womenOnly: false,
      hostAttestsPaidOk: true,
      status: "open",
      code: "7740",
      codeRevealedAt: null,
    },
    {
      id: "seed-mon-am",
      seedSlot: "mon-am",
      hostId: "sam",
      venueId: "katy",
      activity: "run",
      title: "Pre-work Katy miles",
      detail: "Steady 7:30s. One seat. I’ll be at the Reverchon pin.",
      startAt: nextWeekday(now, 1, 5, 45).toISOString(),
      durationMin: 45,
      capacity: 2,
      priceCents: 1800,
      visibility: "public",
      joinMode: "approve",
      womenOnly: false,
      hostAttestsPaidOk: true,
      status: "open",
      code: "1933",
      codeRevealedAt: null,
    },
    {
      id: "seed-tue-am",
      seedSlot: "tue-am",
      hostId: "maya",
      venueId: "katy",
      activity: "run",
      title: "Tuesday 6am — already going",
      detail: "Same loop as always. Hold the slot if you’ll be there.",
      startAt: nextWeekday(now, 2, 6, 0).toISOString(),
      durationMin: 40,
      capacity: 2,
      priceCents: 1500,
      visibility: "public",
      joinMode: "approve",
      womenOnly: false,
      hostAttestsPaidOk: true,
      status: "open",
      code: "6502",
      codeRevealedAt: null,
    },
    {
      id: "seed-wed-women",
      seedSlot: "wed-women",
      hostId: "priya",
      venueId: "whiterock",
      activity: "run",
      title: "Women-only easy lake miles",
      detail: "Talking pace. Women-only listing. No programming.",
      startAt: nextWeekday(now, 3, 6, 10).toISOString(),
      durationMin: 50,
      capacity: 3,
      priceCents: 1200,
      visibility: "public",
      joinMode: "approve",
      womenOnly: true,
      hostAttestsPaidOk: true,
      status: "open",
      code: "2208",
      codeRevealedAt: null,
    },
    {
      id: "seed-thu-am",
      seedSlot: "thu-am",
      hostId: "jordan",
      venueId: "whiterock",
      activity: "walk",
      title: "Sunrise lake walk",
      detail: "Brisk, not a race. One open seat.",
      startAt: nextWeekday(now, 4, 6, 15).toISOString(),
      durationMin: 55,
      capacity: 2,
      priceCents: 800,
      visibility: "public",
      joinMode: "approve",
      womenOnly: false,
      hostAttestsPaidOk: true,
      status: "open",
      code: "8814",
      codeRevealedAt: null,
    },
    {
      id: "seed-sat-hike",
      seedSlot: "sat-hike",
      hostId: "jordan",
      venueId: "trinity",
      activity: "hike",
      title: "Saturday Trinity Forest",
      detail: "Nine easy miles. Bring water. GPS will drop — we’ll use the session code.",
      startAt: nextWeekday(now, 6, 8, 0).toISOString(),
      durationMin: 150,
      capacity: 4,
      priceCents: 2000,
      visibility: "public",
      joinMode: "instant",
      womenOnly: false,
      hostAttestsPaidOk: true,
      status: "open",
      code: "3391",
      codeRevealedAt: null,
    },
    {
      id: "seed-invite",
      seedSlot: "invite",
      hostId: ME_ID,
      venueId: "turtle",
      activity: "run",
      title: "Unlisted — invite Dev",
      detail: "Private trailhead. Shared from Messages.",
      startAt: nextWeekday(now, 6, 9, 30).toISOString(),
      durationMin: 40,
      capacity: 2,
      priceCents: 0,
      visibility: "unlisted",
      joinMode: "instant",
      womenOnly: false,
      hostAttestsPaidOk: true,
      status: "open",
      code: "1157",
      codeRevealedAt: null,
    },
  ];
}

function nextLocalEvening(now: Date, hour: number, minute: number) {
  const today = atDallas(now, 0, hour, minute);
  if (today.getTime() > now.getTime() + 30 * 60 * 1000) return today;
  return atDallas(now, 1, hour, minute);
}

export function buildSeedBookings(now: Date): Booking[] {
  return [
    {
      id: "bk-live",
      sessionId: "seed-live",
      participantId: ME_ID,
      status: "confirmed",
      authorizedCents: 1500,
      capturedCents: 0,
      createdAt: new Date(now.getTime() - 36 * 60 * 60 * 1000).toISOString(),
      hostCheckedInAt: null,
      participantCheckedInAt: null,
      checkinMethod: null,
      ratedByParticipant: false,
      ratedByHost: false,
    },
    {
      id: "bk-tue",
      sessionId: "seed-tue-am",
      participantId: ME_ID,
      status: "pending",
      authorizedCents: 1500,
      capturedCents: 0,
      createdAt: now.toISOString(),
      hostCheckedInAt: null,
      participantCheckedInAt: null,
      checkinMethod: null,
      ratedByParticipant: false,
      ratedByHost: false,
    },
    {
      id: "bk-past",
      sessionId: "seed-past",
      participantId: ME_ID,
      status: "completed",
      authorizedCents: 1500,
      capturedCents: 1500,
      createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      hostCheckedInAt: new Date(now.getTime() - 50 * 60 * 60 * 1000).toISOString(),
      participantCheckedInAt: new Date(
        now.getTime() - 50 * 60 * 60 * 1000,
      ).toISOString(),
      checkinMethod: "geo",
      ratedByParticipant: true,
      ratedByHost: true,
    },
  ];
}

export function buildSeedMessages(now: Date): ChatMessage[] {
  return [
    {
      id: "m1",
      bookingId: "bk-live",
      fromId: "maya",
      text: "I’ll be at the Reverchon pin. Easy pace — I already ran yesterday.",
      createdAt: new Date(now.getTime() - 80 * 60 * 1000).toISOString(),
    },
    {
      id: "m2",
      bookingId: "bk-live",
      fromId: ME_ID,
      text: "On the trail in ten. Holding the slot.",
      createdAt: new Date(now.getTime() - 70 * 60 * 1000).toISOString(),
    },
    {
      id: "m3",
      bookingId: "bk-tue",
      fromId: "maya",
      text: "Got your request for Tuesday. Same trailhead as today.",
      createdAt: new Date(now.getTime() - 20 * 60 * 1000).toISOString(),
    },
  ];
}

export function personById(id: string) {
  return people.find((p) => p.id === id);
}

export function venueById(id: string) {
  return venues.find((v) => v.id === id);
}
