/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HealthRouteImport } from './routes/health'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as PostRouteImport } from './routes/post'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrototypeRouteImport } from './routes/prototype'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as YouRouteImport } from './routes/you'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronSettleRouteImport } from './routes/api/cron/settle'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeRoute = PrototypeRouteImport.update({
  id: '/prototype',
  path: '/prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InboxRoute,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InboxRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessionsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSettleRoute = ApiCronSettleRouteImport.update({
  id: '/api/cron/settle',
  path: '/api/cron/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRouteWithChildren
  '/post': typeof PostRoute
  '/privacy': typeof PrivacyRoute
  '/prototype': typeof PrototypeRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/you': typeof YouRoute
  '/inbox/$id': typeof InboxIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/live/$id': typeof LiveIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/inbox/': typeof InboxIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/settle': typeof ApiCronSettleRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/health': typeof HealthRoute
  '/post': typeof PostRoute
  '/privacy': typeof PrivacyRoute
  '/prototype': typeof PrototypeRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/you': typeof YouRoute
  '/inbox/$id': typeof InboxIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/live/$id': typeof LiveIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/inbox': typeof InboxIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/settle': typeof ApiCronSettleRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRouteWithChildren
  '/post': typeof PostRoute
  '/privacy': typeof PrivacyRoute
  '/prototype': typeof PrototypeRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/you': typeof YouRoute
  '/inbox/$id': typeof InboxIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/live/$id': typeof LiveIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/inbox/': typeof InboxIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/settle': typeof ApiCronSettleRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/health'
    | '/inbox'
    | '/post'
    | '/privacy'
    | '/prototype'
    | '/sessions'
    | '/support'
    | '/terms'
    | '/you'
    | '/inbox/$id'
    | '/invite/$code'
    | '/live/$id'
    | '/sessions/$id'
    | '/inbox/'
    | '/sessions/'
    | '/api/auth/$'
    | '/api/cron/settle'
    | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/health'
    | '/post'
    | '/privacy'
    | '/prototype'
    | '/support'
    | '/terms'
    | '/you'
    | '/inbox/$id'
    | '/invite/$code'
    | '/live/$id'
    | '/sessions/$id'
    | '/inbox'
    | '/sessions'
    | '/api/auth/$'
    | '/api/cron/settle'
    | '/api/v1/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/health'
    | '/inbox'
    | '/post'
    | '/privacy'
    | '/prototype'
    | '/sessions'
    | '/support'
    | '/terms'
    | '/you'
    | '/inbox/$id'
    | '/invite/$code'
    | '/live/$id'
    | '/sessions/$id'
    | '/inbox/'
    | '/sessions/'
    | '/api/auth/$'
    | '/api/cron/settle'
    | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HealthRoute: typeof HealthRoute
  InboxRoute: typeof InboxRouteWithChildren
  PostRoute: typeof PostRoute
  PrivacyRoute: typeof PrivacyRoute
  PrototypeRoute: typeof PrototypeRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  YouRoute: typeof YouRoute
  InviteCodeRoute: typeof InviteCodeRoute
  LiveIdRoute: typeof LiveIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronSettleRoute: typeof ApiCronSettleRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype': {
      id: '/prototype'
      path: '/prototype'
      fullPath: '/prototype'
      preLoaderRoute: typeof PrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof InboxRoute
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/settle': {
      id: '/api/cron/settle'
      path: '/api/cron/settle'
      fullPath: '/api/cron/settle'
      preLoaderRoute: typeof ApiCronSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InboxRouteChildren {
  InboxIdRoute: typeof InboxIdRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxIdRoute: InboxIdRoute,
  InboxIndexRoute: InboxIndexRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

interface SessionsRouteChildren {
  SessionsIdRoute: typeof SessionsIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsIdRoute: SessionsIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HealthRoute: HealthRoute,
  InboxRoute: InboxRouteWithChildren,
  PostRoute: PostRoute,
  PrivacyRoute: PrivacyRoute,
  PrototypeRoute: PrototypeRoute,
  SessionsRoute: SessionsRouteWithChildren,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  YouRoute: YouRoute,
  InviteCodeRoute: InviteCodeRoute,
  LiveIdRoute: LiveIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronSettleRoute: ApiCronSettleRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
