/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as PostRouteImport } from './routes/post'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as YouRouteImport } from './routes/you'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InboxRoute,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InboxRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRouteWithChildren
  '/post': typeof PostRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/you': typeof YouRoute
  '/inbox/$id': typeof InboxIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/live/$id': typeof LiveIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/inbox/': typeof InboxIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/post': typeof PostRoute
  '/you': typeof YouRoute
  '/inbox/$id': typeof InboxIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/live/$id': typeof LiveIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/inbox': typeof InboxIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRouteWithChildren
  '/post': typeof PostRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/you': typeof YouRoute
  '/inbox/$id': typeof InboxIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/live/$id': typeof LiveIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/inbox/': typeof InboxIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/inbox'
    | '/post'
    | '/sessions'
    | '/you'
    | '/inbox/$id'
    | '/invite/$code'
    | '/live/$id'
    | '/sessions/$id'
    | '/inbox/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/post'
    | '/you'
    | '/inbox/$id'
    | '/invite/$code'
    | '/live/$id'
    | '/sessions/$id'
    | '/inbox'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/inbox'
    | '/post'
    | '/sessions'
    | '/you'
    | '/inbox/$id'
    | '/invite/$code'
    | '/live/$id'
    | '/sessions/$id'
    | '/inbox/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  InboxRoute: typeof InboxRouteWithChildren
  PostRoute: typeof PostRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  YouRoute: typeof YouRoute
  InviteCodeRoute: typeof InviteCodeRoute
  LiveIdRoute: typeof LiveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof InboxRoute
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof SessionsRoute
    }
  }
}

interface InboxRouteChildren {
  InboxIdRoute: typeof InboxIdRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxIdRoute: InboxIdRoute,
  InboxIndexRoute: InboxIndexRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

interface SessionsRouteChildren {
  SessionsIdRoute: typeof SessionsIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsIdRoute: SessionsIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  InboxRoute: InboxRouteWithChildren,
  PostRoute: PostRoute,
  SessionsRoute: SessionsRouteWithChildren,
  YouRoute: YouRoute,
  InviteCodeRoute: InviteCodeRoute,
  LiveIdRoute: LiveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
