/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BillingReturnRouteImport } from './routes/billing-return'
import { Route as HealthRouteImport } from './routes/health'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as PostRouteImport } from './routes/post'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrototypeRouteImport } from './routes/prototype'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifiedRouteImport } from './routes/verified'
import { Route as YouRouteImport } from './routes/you'
import { Route as DotwellKnownAgentCardDotjsonRouteImport } from './routes/[.]well-known.agent-card[.]json'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known.apple-app-site-association'
import { Route as DotwellKnownAssetlinksDotjsonRouteImport } from './routes/[.]well-known.assetlinks[.]json'
import { Route as ApiA2aRouteImport } from './routes/api/a2a'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as TrainingBlockIdRouteImport } from './routes/training-block.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronSettleRouteImport } from './routes/api/cron/settle'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiWebhooksPersonaRouteImport } from './routes/api/webhooks/persona'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingReturnRoute = BillingReturnRouteImport.update({
  id: '/billing-return',
  path: '/billing-return',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeRoute = PrototypeRouteImport.update({
  id: '/prototype',
  path: '/prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiedRoute = VerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentCardDotjsonRoute =
  DotwellKnownAgentCardDotjsonRouteImport.update({
    id: '/.well-known/agent-card.json',
    path: '/.well-known/agent-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAssetlinksDotjsonRoute =
  DotwellKnownAssetlinksDotjsonRouteImport.update({
    id: '/.well-known/assetlinks.json',
    path: '/.well-known/assetlinks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiA2aRoute = ApiA2aRouteImport.update({
  id: '/api/a2a',
  path: '/api/a2a',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InboxRoute,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InboxRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessionsRoute,
} as any)
const TrainingBlockIdRoute = TrainingBlockIdRouteImport.update({
  id: '/training-block/$id',
  path: '/training-block/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSettleRoute = ApiCronSettleRouteImport.update({
  id: '/api/cron/settle',
  path: '/api/cron/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPersonaRoute = ApiWebhooksPersonaRouteImport.update({
  id: '/api/webhooks/persona',
  path: '/api/webhooks/persona',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing-return': typeof BillingReturnRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRouteWithChildren
  '/post': typeof PostRoute
  '/privacy': typeof PrivacyRoute
  '/prototype': typeof PrototypeRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verified': typeof VerifiedRoute
  '/you': typeof YouRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/api/a2a': typeof ApiA2aRoute
  '/inbox/$id': typeof InboxIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/live/$id': typeof LiveIdRoute
  '/session/$id': typeof SessionIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/training-block/$id': typeof TrainingBlockIdRoute
  '/inbox/': typeof InboxIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/settle': typeof ApiCronSettleRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/webhooks/persona': typeof ApiWebhooksPersonaRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing-return': typeof BillingReturnRoute
  '/health': typeof HealthRoute
  '/post': typeof PostRoute
  '/privacy': typeof PrivacyRoute
  '/prototype': typeof PrototypeRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verified': typeof VerifiedRoute
  '/you': typeof YouRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/api/a2a': typeof ApiA2aRoute
  '/inbox/$id': typeof InboxIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/live/$id': typeof LiveIdRoute
  '/session/$id': typeof SessionIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/training-block/$id': typeof TrainingBlockIdRoute
  '/inbox': typeof InboxIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/settle': typeof ApiCronSettleRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/webhooks/persona': typeof ApiWebhooksPersonaRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing-return': typeof BillingReturnRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRouteWithChildren
  '/post': typeof PostRoute
  '/privacy': typeof PrivacyRoute
  '/prototype': typeof PrototypeRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verified': typeof VerifiedRoute
  '/you': typeof YouRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/api/a2a': typeof ApiA2aRoute
  '/inbox/$id': typeof InboxIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/live/$id': typeof LiveIdRoute
  '/session/$id': typeof SessionIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/training-block/$id': typeof TrainingBlockIdRoute
  '/inbox/': typeof InboxIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/settle': typeof ApiCronSettleRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/webhooks/persona': typeof ApiWebhooksPersonaRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/billing-return'
    | '/health'
    | '/inbox'
    | '/post'
    | '/privacy'
    | '/prototype'
    | '/sessions'
    | '/support'
    | '/terms'
    | '/verified'
    | '/you'
    | '/.well-known/agent-card.json'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/api/a2a'
    | '/inbox/$id'
    | '/invite/$code'
    | '/live/$id'
    | '/session/$id'
    | '/sessions/$id'
    | '/training-block/$id'
    | '/inbox/'
    | '/sessions/'
    | '/api/auth/$'
    | '/api/cron/settle'
    | '/api/v1/$'
    | '/api/webhooks/persona'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/billing-return'
    | '/health'
    | '/post'
    | '/privacy'
    | '/prototype'
    | '/support'
    | '/terms'
    | '/verified'
    | '/you'
    | '/.well-known/agent-card.json'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/api/a2a'
    | '/inbox/$id'
    | '/invite/$code'
    | '/live/$id'
    | '/session/$id'
    | '/sessions/$id'
    | '/training-block/$id'
    | '/inbox'
    | '/sessions'
    | '/api/auth/$'
    | '/api/cron/settle'
    | '/api/v1/$'
    | '/api/webhooks/persona'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/billing-return'
    | '/health'
    | '/inbox'
    | '/post'
    | '/privacy'
    | '/prototype'
    | '/sessions'
    | '/support'
    | '/terms'
    | '/verified'
    | '/you'
    | '/.well-known/agent-card.json'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/api/a2a'
    | '/inbox/$id'
    | '/invite/$code'
    | '/live/$id'
    | '/session/$id'
    | '/sessions/$id'
    | '/training-block/$id'
    | '/inbox/'
    | '/sessions/'
    | '/api/auth/$'
    | '/api/cron/settle'
    | '/api/v1/$'
    | '/api/webhooks/persona'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BillingReturnRoute: typeof BillingReturnRoute
  HealthRoute: typeof HealthRoute
  InboxRoute: typeof InboxRouteWithChildren
  PostRoute: typeof PostRoute
  PrivacyRoute: typeof PrivacyRoute
  PrototypeRoute: typeof PrototypeRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VerifiedRoute: typeof VerifiedRoute
  YouRoute: typeof YouRoute
  DotwellKnownAgentCardDotjsonRoute: typeof DotwellKnownAgentCardDotjsonRoute
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  DotwellKnownAssetlinksDotjsonRoute: typeof DotwellKnownAssetlinksDotjsonRoute
  ApiA2aRoute: typeof ApiA2aRoute
  InviteCodeRoute: typeof InviteCodeRoute
  LiveIdRoute: typeof LiveIdRoute
  SessionIdRoute: typeof SessionIdRoute
  TrainingBlockIdRoute: typeof TrainingBlockIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronSettleRoute: typeof ApiCronSettleRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiWebhooksPersonaRoute: typeof ApiWebhooksPersonaRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing-return': {
      id: '/billing-return'
      path: '/billing-return'
      fullPath: '/billing-return'
      preLoaderRoute: typeof BillingReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype': {
      id: '/prototype'
      path: '/prototype'
      fullPath: '/prototype'
      preLoaderRoute: typeof PrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified': {
      id: '/verified'
      path: '/verified'
      fullPath: '/verified'
      preLoaderRoute: typeof VerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-card.json': {
      id: '/.well-known/agent-card.json'
      path: '/.well-known/agent-card.json'
      fullPath: '/.well-known/agent-card.json'
      preLoaderRoute: typeof DotwellKnownAgentCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/assetlinks.json': {
      id: '/.well-known/assetlinks.json'
      path: '/.well-known/assetlinks.json'
      fullPath: '/.well-known/assetlinks.json'
      preLoaderRoute: typeof DotwellKnownAssetlinksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a2a': {
      id: '/api/a2a'
      path: '/api/a2a'
      fullPath: '/api/a2a'
      preLoaderRoute: typeof ApiA2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof InboxRoute
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/training-block/$id': {
      id: '/training-block/$id'
      path: '/training-block/$id'
      fullPath: '/training-block/$id'
      preLoaderRoute: typeof TrainingBlockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/settle': {
      id: '/api/cron/settle'
      path: '/api/cron/settle'
      fullPath: '/api/cron/settle'
      preLoaderRoute: typeof ApiCronSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/persona': {
      id: '/api/webhooks/persona'
      path: '/api/webhooks/persona'
      fullPath: '/api/webhooks/persona'
      preLoaderRoute: typeof ApiWebhooksPersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InboxRouteChildren {
  InboxIdRoute: typeof InboxIdRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxIdRoute: InboxIdRoute,
  InboxIndexRoute: InboxIndexRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

interface SessionsRouteChildren {
  SessionsIdRoute: typeof SessionsIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsIdRoute: SessionsIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BillingReturnRoute: BillingReturnRoute,
  HealthRoute: HealthRoute,
  InboxRoute: InboxRouteWithChildren,
  PostRoute: PostRoute,
  PrivacyRoute: PrivacyRoute,
  PrototypeRoute: PrototypeRoute,
  SessionsRoute: SessionsRouteWithChildren,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VerifiedRoute: VerifiedRoute,
  YouRoute: YouRoute,
  DotwellKnownAgentCardDotjsonRoute: DotwellKnownAgentCardDotjsonRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  DotwellKnownAssetlinksDotjsonRoute: DotwellKnownAssetlinksDotjsonRoute,
  ApiA2aRoute: ApiA2aRoute,
  InviteCodeRoute: InviteCodeRoute,
  LiveIdRoute: LiveIdRoute,
  SessionIdRoute: SessionIdRoute,
  TrainingBlockIdRoute: TrainingBlockIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronSettleRoute: ApiCronSettleRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiWebhooksPersonaRoute: ApiWebhooksPersonaRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
